# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ba521b2b392a788b0f7eba71bebd66a2bd12e9a494ba9315e59dca340447c83be3fa0c4edadca42b6cd6d5ae3326386dec125580af8b4fad236720dc2d9d722

test:
  secret_key_base: 298ad47f497166ee2f17a7b29aed2c427a7e584dac5012c8d8c5dd60362c156650698769b00ccd8c02fb29e165822338546adb001cae04c35c708e07da885f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
